name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'  # Cambia a la versión de Terraform que necesites

      # Step 3: Set up AWS OIDC credentials
      - name: Set up AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::918691367691:role/GithubActionWorkflowOICD
          aws-region: us-east-1
          role-session-name: GitHubActions

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Apply and capture output
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve
          USER_NAME=$(terraform output -raw user_name)
          echo "USER_NAME=${USER_NAME}" >> $GITHUB_ENV

      # Step 6: Generate credentials file
      - name: Generate Credentials File
        run: |
          echo "Access Key ID: $(terraform output -raw access_key_id)" > ${USER_NAME}_credentials.txt
          echo "Secret Access Key: $(terraform output -raw access_key_secret)" >> ${USER_NAME}_credentials.txt
          echo "User Name: ${USER_NAME}" >> ${USER_NAME}_credentials.txt

      # Step 7: Upload Credentials
      - name: Upload Credentials
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.USER_NAME }}-credentials
          path: "${{ env.USER_NAME }}_credentials.txt"
          retention-days: 1
