
name: Terraform Plan and Apply

on:
  pull_request:
    branches:
      - main  # Ejecutar solo si el pull request apunta a la rama main
    paths:
      - terraform.tfvars  # Ejecutar solo si hay cambios en terraform.tfvars

permissions:
  id-token: write
  contents: read  # Necesario para acciones que leen el contenido del repositorio

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Verificar si terraform.tfvars ha cambiado
      - name: Check if terraform.tfvars has changed
        id: check_tfvars
        run: |
          git fetch origin main
          if git diff --quiet origin/main -- terraform.tfvars; then
            echo "No changes detected in terraform.tfvars, skipping workflow."
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "terraform.tfvars has changed, proceeding with the workflow."
            echo "continue=true" >> $GITHUB_ENV
          fi


      # Paso 3: Continuar solo si hay cambios en terraform.tfvars
      - name: Exit if no changes in terraform.tfvars
        if: env.continue == 'false'
        run: exit 0

      # Paso 4: Instalar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      # Paso 5: Extraer el Account ID desde terraform.tfvars
      - name: Extract AWS Account ID
        id: extract_account_id
        run: |
          account_id=$(grep 'account_id' terraform.tfvars | awk -F'=' '{print $2}' | tr -d ' "')
          echo "AWS_ACCOUNT_ID=${account_id}" >> $GITHUB_ENV

      # Paso 6: Configurar las credenciales de AWS OIDC
      - name: Set up AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: us-east-1
          role-session-name: GitHubActions

      # Paso 7: Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # Paso 8: Aplicar Terraform
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve
          echo "::notice title=Terraform Apply Completed::Successfully applied Terraform changes"

      # Paso 9: Capturar las salidas de Terraform y exportarlas como variables de entorno
      - name: Capture Terraform Outputs
        run: |
          echo "USER_NAME=$(terraform output -raw user_name)" >> $GITHUB_ENV
          echo "ACCESS_KEY_ID=$(terraform output -raw access_key_id)" >> $GITHUB_ENV
          echo "ACCESS_KEY_SECRET=$(terraform output -raw access_key_secret)" >> $GITHUB_ENV

      # Paso 10: Crear el archivo con la información del usuario
      - name: Create User Info File
        run: |
          echo "Buenas tardes," > user_info.txt
          echo "" >> user_info.txt
          echo "Se ha creado el usuario con los siguientes datos:" >> user_info.txt
          echo "User name: $USER_NAME" >> user_info.txt
          echo "Access key id: $ACCESS_KEY_ID" >> user_info.txt
          echo "Access key secret: $ACCESS_KEY_SECRET" >> user_info.txt
          echo "" >> user_info.txt
          echo "Recordad que hay que pegar esta clave en el campo seguro." >> user_info.txt
          echo "" >> user_info.txt
          echo "Un saludo." >> user_info.txt

      # Paso 11: Subir el archivo como un artefacto
      - name: Upload User Info as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: user-info
          path: user_info.txt
          retention-days: 1

