
name: Terraform Plan and Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Instalar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      # Paso 3: Extraer el Account ID desde terraform.tfvars
      - name: Extract AWS Account ID
        id: extract_account_id
        run: |
          # Extraer el valor de "account_id" desde terraform.tfvars
          account_id=$(grep "account_id" terraform.tfvars | awk -F'=' '{print $2}' | tr -d ' "')
          echo "AWS_ACCOUNT_ID=${account_id}"
          echo "AWS_ACCOUNT_ID=${account_id}" >> $GITHUB_ENV

      # Paso 4: Configurar credenciales de AWS OIDC
      - name: Set up AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: us-east-1
          role-session-name: GitHubActions

      # Paso 5: Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # Paso 6: Aplicar Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
