name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  secrets: write  # Allow access to write secrets to GitHub

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      # Step 3: Set up AWS OIDC credentials
      - name: Set up AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::918691367691:role/GithubActionWorkflowOICD
          aws-region: us-east-1
          role-session-name: GitHubActions

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Apply and Capture Output
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve
          echo "::notice title=Terraform Apply Completed::Successfully applied Terraform changes"
          
          # Capture the Terraform output values
          USER_NAME=$(terraform output -raw user_name)
          ACCESS_KEY_ID=$(terraform output -raw access_key_id)
          ACCESS_KEY_SECRET=$(terraform output -raw access_key_secret)

          # Store the Terraform generated keys as GitHub Secrets using the GitHub API
          echo "Storing AWS access keys as GitHub Secrets..."

          # GitHub API URL for Secrets
          GITHUB_API_URL="https://api.github.com/repos/${{ github.repository }}/actions/secrets"
          
          # Encode the Access Key ID and Secret Access Key (required for GitHub API)
          ACCESS_KEY_ID_ENCODED=$(echo -n "$ACCESS_KEY_ID" | base64)
          ACCESS_KEY_SECRET_ENCODED=$(echo -n "$ACCESS_KEY_SECRET" | base64)

          # Store the secrets in GitHub using GitHub's REST API
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"encrypted_value\":\"$ACCESS_KEY_ID_ENCODED\", \"key_id\":\"$KEY_ID\"}" \
            "$GITHUB_API_URL/AWS_ACCESS_KEY_ID"
          
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"encrypted_value\":\"$ACCESS_KEY_SECRET_ENCODED\", \"key_id\":\"$KEY_ID\"}" \
            "$GITHUB_API_URL/AWS_SECRET_ACCESS_KEY"
          
          echo "AWS keys successfully stored in GitHub Secrets"

      # Step 6: Use the values in a subsequent step (example)
      - name: Display User Information
        run: |
          echo "User Name: ${{ steps.apply.outputs.user_name }}"
          echo "Access Key ID: ${{ steps.apply.outputs.access_key_id }}"
          echo "Access Key Secret: ${{ steps.apply.outputs.access_key_secret }}"
