name: Terraform Plan and Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      # Step 3: Set up AWS OIDC credentials
      - name: Set up AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::918691367691:role/GithubActionWorkflowOICD
          aws-region: us-east-1
          role-session-name: GitHubActions

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Apply and Capture Output with Wrapper
      - name: Terraform Apply
        id: apply
        run: |
          chmod +x ./terraform-wrapper.sh
          ./terraform-wrapper.sh apply -auto-approve

          # Captura los valores formateados
          ./terraform-wrapper.sh output > user_info.txt

          # Agrega encabezado y pie al archivo
          sed -i '1i Buenas tardes,\n\nSe ha creado el usuario con los siguientes datos:' user_info.txt
          echo -e "\nRecordad que hay que pegar esta clave en el campo seguro.\n\nUn saludo." >> user_info.txt

      # Step 6: Upload the file as an artifact
      - name: Upload User Info as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: user-info
          path: user_info.txt
