name: Terraform Plan and Apply

on:
  pull_request:
    paths:
      - terraform.tfvars  # Ejecutar solo si hay cambios en terraform.tfvars
    branches:
      - main  # Solo para pull requests dirigidos a la rama main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Verificar si terraform.tfvars ha cambiado
      - name: Check if terraform.tfvars has changed
        id: check_tfvars
        run: |
          git fetch origin main
          if ! git diff --quiet origin/main -- terraform.tfvars; then
            echo "terraform.tfvars has changed, proceeding with the workflow"
          else
            echo "No changes detected in terraform.tfvars, skipping workflow."
            exit 0  # Skip the workflow if no changes in terraform.tfvars
          fi

      # Paso 3: Instalar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      # Paso 4: Extraer account_id desde Terraform variables
      - name: Extract AWS Account ID
        run: |
          # Inicializar Terraform
          terraform init
          
          # Ejecutar Terraform console para obtener account_id
          ACCOUNT_ID=$(terraform console <<< 'var.account_id')
          
          # Exportar la variable para usarla en los siguientes pasos
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      # Paso 5: Configurar las credenciales de AWS OIDC
      - name: Set up AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: us-east-1
          role-session-name: GitHubActions

      # Paso 6: Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # Paso 7: Aplicar Terraform y capturar las salidas
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve
          echo "::notice title=Terraform Apply Completed::Successfully applied Terraform changes"
          
          # Capturar las salidas de Terraform y exportarlas como variables de entorno
          echo "USER_NAME=$(terraform output -raw user_name)" >> $GITHUB_ENV
          echo "ACCESS_KEY_ID=$(terraform output -raw access_key_id)" >> $GITHUB_ENV
          echo "ACCESS_KEY_SECRET=$(terraform output -raw access_key_secret)" >> $GITHUB_ENV

      # Paso 8: Crear el archivo con la información del usuario
      - name: Create User Info File
        run: |
          echo "Buenas tardes," > user_info.txt
          echo "" >> user_info.txt
          echo "Se ha creado el usuario con los siguientes datos:" >> user_info.txt
          echo "User name: $USER_NAME" >> user_info.txt
          echo "Access key id: $ACCESS_KEY_ID" >> user_info.txt
          echo "Access secret key: $ACCESS_KEY_SECRET" >> user_info.txt
          echo "" >> user_info.txt
          echo "Recordad que hay que pegar esta clave en el campo seguro." >> user_info.txt
          echo "" >> user_info.txt
          echo "Un saludo." >> user_info.txt

      # Paso 9: Subir el archivo como un artefacto
      - name: Upload User Info as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: user-info
          path: user_info.txt
          retention-days: 1

